export const links = [
    { title: "Algebron Documentation", url: "/pages/algebron" },
    { title: "Precalculus", url: "/pages/precalculus" },
    { title: "Geometry", url: "/pages/geometry" },
    { title: "Set Theory", url: "/pages/set-theory" },
    { title: "Calculus", url: "/pages/calculus" },
    { title: "Classical Mechanics", url: "/pages/classical-mechanics" },
    { title: "Electromagnetism", url: "/pages/electromagnetism" },
    { title: "Complex Analysis", url: "/pages/complex-analysis" },
    { title: "Linear Algebra", url: "/pages/linear-algebra" },
    { title: "Number Theory", url: "/pages/number-theory" },
    { title: "Combinatorics", url: "/pages/combinatorics" },
    { title: "Probability", url: "/pages/probability" },
    { title: "Numerical Analysis", url: "/pages/numerical-analysis" },
];
